# Numpy

In [2]:
import numpy as np

## Numpy Array

In [3]:
benimListem = [20, 30, 40]

In [4]:
type(benimListem)

list

In [5]:
np.array(benimListem)

array([20, 30, 40])

In [6]:
type(np.array(benimListem))

numpy.ndarray

In [7]:
matrixListesi = [[10,20,30],[20,30,40],[30,40,50]]

In [8]:
type(matrixListesi)

list

In [9]:
matrixListesi[1]

[20, 30, 40]

In [10]:
matrixListesi[1][0]

20

In [11]:
np.array(matrixListesi)

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50]])

## Numpy Methodlar

### arange

In [12]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [13]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

### zeros

In [15]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [16]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

### ones

In [17]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [19]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### linspace

In [24]:
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

In [23]:
np.linspace(0,20,6)

array([ 0.,  4.,  8., 12., 16., 20.])

In [30]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [31]:
np.linspace(1,100,100)

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
        23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,
        34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,
        45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,
        56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,
        67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,
        78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
        89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.,
       100.])

### eye

In [32]:
np.eye(3) # birim matris

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### random

In [35]:
np.random.randn(4)

array([1.1945949 , 1.3498233 , 0.63889204, 1.03301785])

In [37]:
np.random.randn(4,4)

array([[-0.59922375, -0.98447278,  2.28961147, -0.58557186],
       [-0.41771432, -0.41121028,  0.89891834,  0.55693015],
       [ 0.15781286,  0.181682  , -1.25115179, -0.73504238],
       [ 0.30210068, -0.03908841,  0.35479597,  1.04203761]])

In [38]:
np.random.randint(1,10)

6

In [40]:
np.random.randint(1,10,5)

array([1, 3, 5, 9, 8])

In [41]:
benimNumpyDizim = np.arange(30)

In [42]:
benimNumpyDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [46]:
benimRandomDizim = np.random.randint(0,100,30)

In [47]:
benimRandomDizim

array([56, 14, 95,  0, 51, 98, 89, 82, 54, 36, 69, 29, 28, 21, 31, 21, 81,
       21, 55,  6, 10,  6, 78, 91, 54, 86, 35, 62, 31, 52])

## Numpy Dizi Methodları


In [49]:
benimNumpyDizim.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [50]:
benimNumpyDizim.reshape(6,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [58]:
benimNumpyDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [59]:
reshapeDizim = benimNumpyDizim.reshape(6,5)

In [60]:
reshapeDizim

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [61]:
benimNumpyDizim.shape

(30,)

In [62]:
reshapeDizim.shape

(6, 5)

In [51]:
benimNumpyDizim.max()

29

In [52]:
benimRandomDizim.max()

98

In [54]:
benimRandomDizim.argmax() # maks değerin indexini söylüyor

5

In [56]:
benimRandomDizim.min()

0

In [57]:
benimRandomDizim.argmin() # min değerin indexini söylüyor

3