# Numpy İndeksler, Matrix İndeksler, Numpy Operasyonlar

## Numpy Indexler

In [2]:
import numpy as np

In [3]:
benimDizim = np.arange(0,15)

In [4]:
benimDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [5]:
benimDizim[5]

5

In [6]:
benimDizim[3:5]

array([3, 4])

In [7]:
benimDizim[3:8] = -5

In [8]:
benimDizim

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9, 10, 11, 12, 13, 14])

In [9]:
baskaDizi = np.arange(0,24)

In [10]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [11]:
slicingDizisi = baskaDizi[4:9]

In [12]:
slicingDizisi

array([4, 5, 6, 7, 8])

In [13]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [14]:
slicingDizisi[:] = 700 

In [15]:
slicingDizisi

array([700, 700, 700, 700, 700])

In [16]:
baskaDizi

array([  0,   1,   2,   3, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [31]:
ornekDizi = np.arange(0,24)

In [32]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [33]:
ornekDiziKopyasi = ornekDizi.copy()

In [34]:
ornekDiziKopyasi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [35]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [41]:
ornekDiziKopyasiSlicing = ornekDiziKopyasi[3:8]

In [42]:
ornekDiziKopyasiSlicing[:] = 800

In [43]:
ornekDiziKopyasiSlicing

array([800, 800, 800, 800, 800])

In [44]:
ornekDiziKopyasi

array([  0,   1,   2, 800, 800, 800, 800, 800,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [45]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

## Matrix Indexler

In [49]:
benimListem = [[10,20,30],[40,50,60],[70,80,90]]

In [50]:
benimMatrixDizim = np.array(benimListem)

In [51]:
benimMatrixDizim

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [52]:
benimMatrixDizim[1][2]

60

In [53]:
benimMatrixDizim[1,2]

60

In [54]:
benimMatrixDizim[1:,2]

array([60, 90])

In [55]:
benimMatrixDizim[0:,2]

array([30, 60, 90])

In [56]:
benimMatrixDizim[0:,1]

array([20, 50, 80])

In [57]:
benimMatrixDizim[0:,1:]

array([[20, 30],
       [50, 60],
       [80, 90]])

In [59]:
yeniListe = [[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14],[15,16,17,18,19],[20,21,22,23,24]]

In [60]:
yeniMatrix = np.array(yeniListe)

In [61]:
yeniMatrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [63]:
yeniMatrix[[0,2,4]]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

In [64]:
yeniMatrix[[4,2,0]]

array([[20, 21, 22, 23, 24],
       [10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4]])

## Numpy Operasyonlar

In [68]:
yeniBirDizi = np.random.randint(1,100,20)

In [69]:
yeniBirDizi

array([62,  2, 92, 49, 15, 31, 57, 48, 66, 27, 14, 56, 12, 22, 63, 62, 93,
       46, 66, 59])

In [70]:
yeniBirDizi > 24

array([ True, False,  True,  True, False,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
        True,  True])

In [71]:
sonucDizisi = yeniBirDizi > 24

In [72]:
sonucDizisi

array([ True, False,  True,  True, False,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
        True,  True])

In [73]:
yeniBirDizi[sonucDizisi]

array([62, 92, 49, 31, 57, 48, 66, 27, 56, 63, 62, 93, 46, 66, 59])

In [74]:
yeniBirDizi[yeniBirDizi > 24]

array([62, 92, 49, 31, 57, 48, 66, 27, 56, 63, 62, 93, 46, 66, 59])

In [75]:
sonDizi = np.arange(0,24)

In [76]:
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [77]:
sonDizi + sonDizi

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [78]:
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [79]:
sonDizi * sonDizi

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [80]:
sonDizi - sonDizi

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [82]:
np.sqrt(sonDizi)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])

In [83]:
np.max(sonDizi)

23

In [84]:
np.min(sonDizi)

0